### ISSUE TITLE
Las dos contraseñas deben ser iguales

### ISSUE THREAD

**Issue by bastideveloper1** [Bastian11111/PROGRAMACIONWEB_4#5]

**Comment by claudmunozb** [comment]
Se implemento en la pagina de registr
![Captura de pantalla 2024-03-22 220551](https://github.com/Bastian11111/PROGRAMACIONWEB_4/assets/145813519/cd975410-7ea4-47fe-9c47-c05cc8ba26ff)
![Captura de pantalla 2024-03-22 220545](https://github.com/Bastian11111/PROGRAMACIONWEB_4/assets/145813519/624462de-2d70-4d1a-8e3f-7c074e815f1c), se comparan ambas contraseñas y si no coinciden envian un mensaje de error al usuario
