### ISSUE TITLE
La contraseña deberá tener un rango de longitud entre 6 y 18 caracteres

### ISSUE THREAD

**Issue by bastideveloper1** [Bastian11111/PROGRAMACIONWEB_4#8]

**Comment by claudmunozb** [comment]
se implementó en la pagina de registro usando un REG EX en los campos HTML donde se solicita la contraseña (2 veces) 
![Captura de pantalla 2024-03-22 195148](https://github.com/Bastian11111/PROGRAMACIONWEB_4/assets/145813519/1b3e2610-ab44-40c7-aae3-d0f39b9448ac)
